name: Twitch Chat Logger

on:
  schedule:
    - cron: '0 * * * *'  # Every hour at minute 0
  workflow_dispatch:

jobs:
  log-chat:
    runs-on: ubuntu-latest
    timeout-minutes: 55  # Stay under 1h limit
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gitpython

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Run Chat Logger
      run: |
        python -u twitch_chat_logger.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Final Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: chat-logs
        path: chat_logs.csv
