name: Twitch Chat Logger

on:
  schedule:
    - cron: '0 * * * *'  # Hourly at minute 0
  workflow_dispatch:

jobs:
  log-chat:
    runs-on: ubuntu-latest
    timeout-minutes: 55
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run Chat Logger
      run: python -u chat_logger.py

    - name: Commit Logs
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add chat_logs3.csv
        git commit -m "Update chat logs [skip ci]" || echo "No changes"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
